sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- ./build.sh
# test image
#- docker run -it thenatureofsoftware/traefik-arm64 version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker push thenatureofsoftware/minio-arm:latest
    docker push thenatureofsoftware/minio-arm64:latest
    docker push thenatureofsoftware/mc-arm:latest
    docker push thenatureofsoftware/mc-arm64:latest
    docker push thenatureofsoftware/mc-mirror-arm:latest
    docker push thenatureofsoftware/mc-mirror-arm64:latest
    .work/manifest-tool --username "$DOCKER_USER" --password "$DOCKER_PASS" push from-spec manifest-minio.yml
    .work/manifest-tool --username "$DOCKER_USER" --password "$DOCKER_PASS" push from-spec manifest-mc.yml
    .work/manifest-tool --username "$DOCKER_USER" --password "$DOCKER_PASS" push from-spec manifest-mc-mirror.yml
  fi
